### ISSUE TITLE
Custom ZMK shield files?

### ISSUE THREAD

**Issue by Brausmith** [davidphilipbarr/Choc-Spaced-Corne#2]
My understanding of KB design is still limited, but I understand that this design doesn't require diodes due to having sufficient pins on the controller board.
Therefore, I imagine that the ZMK shield for this design will have a different config. Do you also have those config files to go with the PCB?

**Comment by davidphilipbarr** [comment]
yeah, it's the same as another board, if it's not on git it's here:

**Comment by Brausmith** [comment]
Based on David's confirmation I got it working.
